# NOTE: update this with your service name
service: indexGenerator

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}

functions:
  index:
    handler: handler.index
    events:
      - http:
          path: api/index/{athleteID}
          method: post
          cors:
            origin: "*"
          request:
            parameters:
              paths:
                athleteID: true
  team_report:
    handler: handler.team_report
    events:
      - http:
          path: api/team_report
          method: post
          cors:
            origin: "*"
